#!/bin/sh

DIR_TARGET=target
rm -rf $DIR_TARGET

PROJECT_NODE=cantata-node
TARGET_NODE=$DIR_TARGET

PROJECT_WEB=cantata-web
TARGET_WEB=$DIR_TARGET/res

PROJECT_JSBIND=cantata-jsbind
TARGET_JSBIND=$TARGET_WEB/routes

PROJECT_NATIVE=cantata-native
TARGET_NATIVE=$DIR_TARGET

git clone git@github.com:bylee/$PROJECT_NODE.git
git clone git@github.com:bylee/$PROJECT_WEB.git
git clone git@github.com:bylee/$PROJECT_JSBIND.git
git clone git@github.com:bylee/$PROJECT_NATIVE.git

mkdir -p $DIR_TARGET
$PROJECT_NODE/build $TARGET_NODE
$PROJECT_WEB/build $TARGET_WEB
$PROJECT_JSBIND/build $TARGET_JSBIND
$PROJECT_NATIVE/build $TARGET_NATIVE

# 사인( Sign )


# 패키징( Packaging )

